// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5p2EUxIsWOh7Ytb26N6CHbtGH2Kb_ZEw',
    appId: '1:959230327096:web:bb99e38cbdd62de953e9cd',
    messagingSenderId: '959230327096',
    projectId: 'mandy2-e0a69',
    authDomain: 'mandy2-e0a69.firebaseapp.com',
    storageBucket: 'mandy2-e0a69.appspot.com',
    measurementId: 'G-FZHYPSKBCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxroVlmXo2FaxBCVeFAzCtYUPbAavmxA0',
    appId: '1:959230327096:android:f0ed53dc7bc122f353e9cd',
    messagingSenderId: '959230327096',
    projectId: 'mandy2-e0a69',
    storageBucket: 'mandy2-e0a69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpUztl6PO8VljJfq0cDksrZlpDktqQVcc',
    appId: '1:959230327096:ios:a660fe31e777945f53e9cd',
    messagingSenderId: '959230327096',
    projectId: 'mandy2-e0a69',
    storageBucket: 'mandy2-e0a69.appspot.com',
    iosBundleId: 'com.example.mandy2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpUztl6PO8VljJfq0cDksrZlpDktqQVcc',
    appId: '1:959230327096:ios:77f90ca1bbf632f353e9cd',
    messagingSenderId: '959230327096',
    projectId: 'mandy2-e0a69',
    storageBucket: 'mandy2-e0a69.appspot.com',
    iosBundleId: 'com.example.mandy2.RunnerTests',
  );
}
